#!/usr/bin/python
from ConfigParser import SafeConfigParser
import sys
from pushbotnotify.notify import Notifier


config = SafeConfigParser()
config.read('/etc/pushbotnotify')

n = Notifier(config.get('pushbotnotify', 'endpoint'),
             config.get('pushbotnotify', 'api_key'))

n.notify(''.join(sys.argv[1:]))
